### PR TITLE
Removing bin and obj folders

### PR DESCRIPTION
**Pull request by pauldendulk**
I was investigating how to turn this into netstandard but ran into some other issues first. This PR is just to remove the binaries and add them to the .gitignore.

### CODE REVIEW

**Comment by AliFlux** [comment]
Thanks for the PR. The reason I included the dlls into the github repo, was that some native dlls were not automatically copied from the VectorTilesRenderer project to the demo projects. So if a person clones this repo and runs the demos, they shouldn't have to face some native dll missing error.

Can you please confirm if you clone the result of this PR and try the demo, it would work?

**Comment by AliFlux** [comment]
I just cloned this PR and it gave me the 

```
Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"} | System.DllNotFoundException
```

The native dll `SQLite.Interop.dll` is not being automatically copied to the demo project. [Here ](https://stackoverflow.com/questions/13028069/unable-to-load-dll-sqlite-interop-dll) are some of the fixes for that.

**Comment by pauldendulk** [comment]
The crash should be fixed by the latest commit in my repo by bert. The demo projects themselves get a reference to the sqllite package.

**Comment by AliFlux** [comment]
Great! I'm merging this.

**Pull request merged**
